package com.sitescout.dsp.api.type;

public enum ConfigParam {
    maxmindcitydb_path,
    maxmindIspDbPath,
    openDdrPath,
    serverURL,
    statsBatchInterval,
    campaignReloadInterval,
    winAuctionRegisterInterval,
    configReloadInterval,
    systemOnline,
    baseCommissionPct,
    fcapEnabled,
    adsHost,
    adsCdnURL,
    adsCdnURLSecure,
    imageStorePath,
    masterJdbcUrl,
    statsJdbcUrl,
    siteStatsEnabled,
    audienceHost,
    profilingEnabled,
    profilingHost,
    profilingPort,
    loggingCappedSize, // in GB
    ssdspVersion,
    defaultAccountRepId,
    pacingReloadInterval,
    pacingOptimizeSleepInterval,
    ssdJdbcUrl,
    minRonBid,
    usePixelSyncBeacon,
    dmpAuctionManCheck,
    expiryRulesEnabled,
    datacraticEnabled,
    hostName,
    restrictCStoWinOnly,
    cseRestrictMode,
    audienceCaptureThrottle,
    audiencePixelThrottle,
    hoverEnabled,
    fileUploaderKey,
    auctionLogHost,
    auctionLogEnabled
}
